apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.replicas | default 2 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        imagePullPolicy: Always
        name: app-2048
        resources: 
          requests:
            cpu: {{ .Values.resources.cpu | default 1 }}
            memory: {{ .Values.resources.memory | default "512Mi" }}
          limits:
            cpu: {{ .Values.resources.cpu | default 1 }}
            memory: {{ .Values.resources.memory | default "512Mi" }}
        ports:
        - containerPort: 80
      topologySpreadConstraints:
      - topologyKey: topology.kubernetes.io/zone
        maxSkew: 1
        minDomains: 2
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .Release.Name }}